# Generated by Django 4.1.3 on 2023-02-05 08:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_order_adress_alter_order_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=48, region=None, verbose_name='Номер телефона'),
        ),
    ]
